/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiclesRouteImport } from './routes/vehicles'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShuttleRouteImport } from './routes/shuttle'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PaymentMethodsRouteImport } from './routes/payment-methods'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryIdRouteImport } from './routes/history.$id'
import { Route as ApiWelcomeRouteImport } from './routes/api/welcome'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout.index'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminRatesRouteImport } from './routes/api/admin/rates'
import { Route as ApiAdminBookingsRouteImport } from './routes/api/admin/bookings'
import { Route as AdminLayoutUsersRouteImport } from './routes/admin/_layout.users'
import { Route as AdminLayoutRatesRouteImport } from './routes/admin/_layout.rates'
import { Route as AdminLayoutBookingsRouteImport } from './routes/admin/_layout.bookings'

const VehiclesRoute = VehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShuttleRoute = ShuttleRouteImport.update({
  id: '/shuttle',
  path: '/shuttle',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentMethodsRoute = PaymentMethodsRouteImport.update({
  id: '/payment-methods',
  path: '/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIdRoute = HistoryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => HistoryRoute,
} as any)
const ApiWelcomeRoute = ApiWelcomeRouteImport.update({
  id: '/api/welcome',
  path: '/api/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRatesRoute = ApiAdminRatesRouteImport.update({
  id: '/api/admin/rates',
  path: '/api/admin/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBookingsRoute = ApiAdminBookingsRouteImport.update({
  id: '/api/admin/bookings',
  path: '/api/admin/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutUsersRoute = AdminLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutRatesRoute = AdminLayoutRatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutBookingsRoute = AdminLayoutBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/driver': typeof DriverRoute
  '/feedback': typeof FeedbackRoute
  '/history': typeof HistoryRouteWithChildren
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/settings': typeof SettingsRoute
  '/shuttle': typeof ShuttleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success': typeof SuccessRoute
  '/summary': typeof SummaryRoute
  '/support': typeof SupportRoute
  '/tracking': typeof TrackingRoute
  '/vehicles': typeof VehiclesRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/welcome': typeof ApiWelcomeRoute
  '/history/$id': typeof HistoryIdRoute
  '/admin/bookings': typeof AdminLayoutBookingsRoute
  '/admin/rates': typeof AdminLayoutRatesRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRoute
  '/api/admin/rates': typeof ApiAdminRatesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/admin/': typeof AdminLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/driver': typeof DriverRoute
  '/feedback': typeof FeedbackRoute
  '/history': typeof HistoryRouteWithChildren
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/settings': typeof SettingsRoute
  '/shuttle': typeof ShuttleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success': typeof SuccessRoute
  '/summary': typeof SummaryRoute
  '/support': typeof SupportRoute
  '/tracking': typeof TrackingRoute
  '/vehicles': typeof VehiclesRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/welcome': typeof ApiWelcomeRoute
  '/history/$id': typeof HistoryIdRoute
  '/admin/bookings': typeof AdminLayoutBookingsRoute
  '/admin/rates': typeof AdminLayoutRatesRoute
  '/admin/users': typeof AdminLayoutUsersRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRoute
  '/api/admin/rates': typeof ApiAdminRatesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/admin': typeof AdminLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/driver': typeof DriverRoute
  '/feedback': typeof FeedbackRoute
  '/history': typeof HistoryRouteWithChildren
  '/login': typeof LoginRoute
  '/payment': typeof PaymentRoute
  '/payment-methods': typeof PaymentMethodsRoute
  '/profile': typeof ProfileRoute
  '/refund': typeof RefundRoute
  '/settings': typeof SettingsRoute
  '/shuttle': typeof ShuttleRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success': typeof SuccessRoute
  '/summary': typeof SummaryRoute
  '/support': typeof SupportRoute
  '/tracking': typeof TrackingRoute
  '/vehicles': typeof VehiclesRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/welcome': typeof ApiWelcomeRoute
  '/history/$id': typeof HistoryIdRoute
  '/admin/_layout/bookings': typeof AdminLayoutBookingsRoute
  '/admin/_layout/rates': typeof AdminLayoutRatesRoute
  '/admin/_layout/users': typeof AdminLayoutUsersRoute
  '/api/admin/bookings': typeof ApiAdminBookingsRoute
  '/api/admin/rates': typeof ApiAdminRatesRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/driver'
    | '/feedback'
    | '/history'
    | '/login'
    | '/payment'
    | '/payment-methods'
    | '/profile'
    | '/refund'
    | '/settings'
    | '/shuttle'
    | '/sitemap.xml'
    | '/success'
    | '/summary'
    | '/support'
    | '/tracking'
    | '/vehicles'
    | '/admin'
    | '/admin/login'
    | '/api/welcome'
    | '/history/$id'
    | '/admin/bookings'
    | '/admin/rates'
    | '/admin/users'
    | '/api/admin/bookings'
    | '/api/admin/rates'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/driver'
    | '/feedback'
    | '/history'
    | '/login'
    | '/payment'
    | '/payment-methods'
    | '/profile'
    | '/refund'
    | '/settings'
    | '/shuttle'
    | '/sitemap.xml'
    | '/success'
    | '/summary'
    | '/support'
    | '/tracking'
    | '/vehicles'
    | '/admin/login'
    | '/api/welcome'
    | '/history/$id'
    | '/admin/bookings'
    | '/admin/rates'
    | '/admin/users'
    | '/api/admin/bookings'
    | '/api/admin/rates'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/driver'
    | '/feedback'
    | '/history'
    | '/login'
    | '/payment'
    | '/payment-methods'
    | '/profile'
    | '/refund'
    | '/settings'
    | '/shuttle'
    | '/sitemap.xml'
    | '/success'
    | '/summary'
    | '/support'
    | '/tracking'
    | '/vehicles'
    | '/admin/_layout'
    | '/admin/login'
    | '/api/welcome'
    | '/history/$id'
    | '/admin/_layout/bookings'
    | '/admin/_layout/rates'
    | '/admin/_layout/users'
    | '/api/admin/bookings'
    | '/api/admin/rates'
    | '/api/admin/users'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/admin/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  DriverRoute: typeof DriverRoute
  FeedbackRoute: typeof FeedbackRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  LoginRoute: typeof LoginRoute
  PaymentRoute: typeof PaymentRoute
  PaymentMethodsRoute: typeof PaymentMethodsRoute
  ProfileRoute: typeof ProfileRoute
  RefundRoute: typeof RefundRoute
  SettingsRoute: typeof SettingsRoute
  ShuttleRoute: typeof ShuttleRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuccessRoute: typeof SuccessRoute
  SummaryRoute: typeof SummaryRoute
  SupportRoute: typeof SupportRoute
  TrackingRoute: typeof TrackingRoute
  VehiclesRoute: typeof VehiclesRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ApiWelcomeRoute: typeof ApiWelcomeRoute
  ApiAdminBookingsRoute: typeof ApiAdminBookingsRoute
  ApiAdminRatesRoute: typeof ApiAdminRatesRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicles': {
      id: '/vehicles'
      path: '/vehicles'
      fullPath: '/vehicles'
      preLoaderRoute: typeof VehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shuttle': {
      id: '/shuttle'
      path: '/shuttle'
      fullPath: '/shuttle'
      preLoaderRoute: typeof ShuttleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-methods': {
      id: '/payment-methods'
      path: '/payment-methods'
      fullPath: '/payment-methods'
      preLoaderRoute: typeof PaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/$id': {
      id: '/history/$id'
      path: '/$id'
      fullPath: '/history/$id'
      preLoaderRoute: typeof HistoryIdRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/api/welcome': {
      id: '/api/welcome'
      path: '/api/welcome'
      fullPath: '/api/welcome'
      preLoaderRoute: typeof ApiWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/rates': {
      id: '/api/admin/rates'
      path: '/api/admin/rates'
      fullPath: '/api/admin/rates'
      preLoaderRoute: typeof ApiAdminRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bookings': {
      id: '/api/admin/bookings'
      path: '/api/admin/bookings'
      fullPath: '/api/admin/bookings'
      preLoaderRoute: typeof ApiAdminBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/users': {
      id: '/admin/_layout/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminLayoutUsersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/rates': {
      id: '/admin/_layout/rates'
      path: '/rates'
      fullPath: '/admin/rates'
      preLoaderRoute: typeof AdminLayoutRatesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/bookings': {
      id: '/admin/_layout/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminLayoutBookingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface HistoryRouteChildren {
  HistoryIdRoute: typeof HistoryIdRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryIdRoute: HistoryIdRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

interface AdminLayoutRouteChildren {
  AdminLayoutBookingsRoute: typeof AdminLayoutBookingsRoute
  AdminLayoutRatesRoute: typeof AdminLayoutRatesRoute
  AdminLayoutUsersRoute: typeof AdminLayoutUsersRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutBookingsRoute: AdminLayoutBookingsRoute,
  AdminLayoutRatesRoute: AdminLayoutRatesRoute,
  AdminLayoutUsersRoute: AdminLayoutUsersRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  DriverRoute: DriverRoute,
  FeedbackRoute: FeedbackRoute,
  HistoryRoute: HistoryRouteWithChildren,
  LoginRoute: LoginRoute,
  PaymentRoute: PaymentRoute,
  PaymentMethodsRoute: PaymentMethodsRoute,
  ProfileRoute: ProfileRoute,
  RefundRoute: RefundRoute,
  SettingsRoute: SettingsRoute,
  ShuttleRoute: ShuttleRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuccessRoute: SuccessRoute,
  SummaryRoute: SummaryRoute,
  SupportRoute: SupportRoute,
  TrackingRoute: TrackingRoute,
  VehiclesRoute: VehiclesRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ApiWelcomeRoute: ApiWelcomeRoute,
  ApiAdminBookingsRoute: ApiAdminBookingsRoute,
  ApiAdminRatesRoute: ApiAdminRatesRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
